### ISSUE TITLE
request: =~ vs match? 

### ISSUE THREAD

**Issue by jasonkarns** [andycandrea/this_or_that.rb#2]
Documenting the different regex match approaches would be nice. Even better, also comparing `string.match? pattern` vs `pattern.match? string`

**Comment by andycandrea** [comment]
Can't believe I forgot to include the items that were actually in the talk. Thanks!

**Comment by jasonkarns** [comment]
This repo/resource is fantastic, btw 😸

**Comment by andycandrea** [comment]
I'm so happy to hear that, thanks!
